apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2023-03-06T10:33:55Z'
  generation: 3
  labels:
    app: elasticsearch
    app.kubernetes.io/instance: dvg-poc
  name: elasticsearch
  namespace: default
  resourceVersion: '17875'
  uid: d93148f5-693f-45ef-b693-7aada7085db7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch
    spec:
      automountServiceAccountToken: true
      containers:
        - env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              value: HCmxAYfGZKcyTRv2
          image: 'elasticsearch:8.6.0'
          imagePullPolicy: IfNotPresent
          name: elasticsearch
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          resources:
            limits:
              cpu: 750m
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 1536Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              mountPropagation: None
              name: elastic-files
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: elastic-files
          persistentVolumeClaim:
            claimName: efs-claim-elasticsearch
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2023-03-06T10:34:27Z'
      lastUpdateTime: '2023-03-06T10:34:27Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2023-03-06T10:33:55Z'
      lastUpdateTime: '2023-03-06T10:34:27Z'
      message: ReplicaSet "elasticsearch-548d6d7d5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
