apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2023-03-06T10:35:33Z'
  name: dvg-poc-apache
  namespace: default
  resourceVersion: '2270'
  uid: a6796ebb-b57f-4d2b-a365-b213f90ca9a3
spec:
  clusterIP: 172.20.73.222
  clusterIPs:
    - 172.20.73.222
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30074
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: dvg-poc-apache
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
