apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2023-03-06T10:34:30Z'
  name: elasticsearch
  namespace: default
  resourceVersion: '2043'
  uid: 35ac602d-2893-44a0-81b1-d3f82fdc77f3
spec:
  clusterIP: 172.20.32.81
  clusterIPs:
    - 172.20.32.81
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: elastic-api
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: elastic-communication
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
